### ISSUE TITLE
Looks like if statement is not necessary

### ISSUE THREAD

**Issue by matiwinnetou** [cardano-foundation/cardano-verify-datasignature#7]
https://github.com/cardano-foundation/cardano-verify-datasignature/blob/6b82c9eeaf611e5fa17eee7ed0e310007fc853b3/index.ts#L63

**Comment by fabianbormann** [comment]
Hey Mati, what would you rewrite here? 🤔 I have 4 cases and I handle one as a default before the if-else-if statements.

**Comment by matiwinnetou** [comment]
Ignore the noise, I misread the code.
