### ISSUE TITLE
Feature parity with java library

### ISSUE THREAD

**Issue by matiwinnetou** [cardano-foundation/cardano-verify-datasignature#8]
Currently missing:

- get message from the data signature envelope
- get stored Cardano address
- get ED 25519 public key and ED 25519 signature encoded in it
- get COSE payload (COSE wrapped message directly signed by the algorithm)

It would be nice to have that library is fully compatible with Sundae Swap's governance system, i.e. should make it easy to extract the following fields: (ED 25519-public key and ED 25519 signature as well as COSE payload) - mentioned above.

**Comment by fabianbormann** [comment]
Hi Mati, let's discuss (maybe in a call) if this requirements should maybe placed in an additional lib because I want to keep things here simple and lightweight.

**Comment by matiwinnetou** [comment]
Sure, we could.

I was thinking of parity to our java library and since to my knowledge this ts library is meant to be used in the server side context - bundle size should not be the issue.

**Comment by fabianbormann** [comment]
Hi Mati, I would now close this issue but more with the intention to put it in something like an "archive" as to mark it as "won't do" and if there is any specific need about this feature from the community I would start working on this 😊
